# Generated by Django 2.1 on 2018-11-09 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCoevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=255)),
                ('seccion', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CursoNombre',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('RUT', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=255)),
                ('coevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Coevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('personaNatural', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aplicacion.PersonaNatural')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('personaNatural', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aplicacion.PersonaNatural')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.CursoNombre'),
        ),
        migrations.AddField(
            model_name='coevaluacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Curso'),
        ),
        migrations.AddField(
            model_name='alumnogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Grupo'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Curso'),
        ),
        migrations.AddField(
            model_name='alumnocoevaluacion',
            name='coevaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Coevaluacion'),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('descripcion', 'coevaluacion')},
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('numero', 'curso'), ('nombre', 'curso')},
        ),
        migrations.AddField(
            model_name='docentecurso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.Docente'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'semestre', 'seccion', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='coevaluacion',
            unique_together={('nombre', 'curso')},
        ),
        migrations.AddField(
            model_name='alumnogrupo',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Alumno'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.Alumno'),
        ),
        migrations.AddField(
            model_name='alumnocoevaluacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='docentecurso',
            unique_together={('docente', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnogrupo',
            unique_together={('alumno', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnocurso',
            unique_together={('alumno', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnocoevaluacion',
            unique_together={('alumno', 'coevaluacion')},
        ),
    ]
