# Generated by Django 2.1 on 2018-11-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alumnogrupo',
            unique_together=set(),
        ),
    ]
