# Generated by Django 2.1 on 2018-11-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181116_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluacion',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coevaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
