# Generated by Django 2.1 on 2018-11-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181120_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluacion',
            name='estado',
            field=models.CharField(choices=[('Respondida', 'Respondida'), ('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada'), ('Publicada', 'Publicada')], max_length=255),
        ),
    ]
