# Generated by Django 2.1 on 2018-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20181120_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluacion',
            name='estado',
            field=models.CharField(choices=[('Contestada', 'Contestada'), ('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada'), ('Publicada', 'Publicada')], max_length=255),
        ),
    ]
