# Generated by Django 2.1 on 2018-11-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20181117_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnogrupo',
            name='pertenece',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
