# Generated by Django 2.1 on 2018-11-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20181120_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorAlumnoCoevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestada', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='aplicacion.Alumno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='aplicacion.Alumno')),
                ('coevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Coevaluacion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='autoralumnocoevaluacion',
            unique_together={('autor', 'alumno', 'coevaluacion')},
        ),
    ]
