# Generated by Django 2.1 on 2018-11-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_auto_20181120_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoralumnocoevaluacion',
            name='contestada',
        ),
    ]
