# Generated by Django 2.1 on 2018-11-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_autoralumnocoevaluacion_contestada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnocoevaluacion',
            name='nota',
        ),
        migrations.AddField(
            model_name='alumnocoevaluacion',
            name='estado',
            field=models.CharField(choices=[('Contestada', 'Contestada'), ('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada'), ('Publicada', 'Publicada')], default='Abierta', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coevaluacion',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Publicada', 'Publicada')], max_length=255),
        ),
    ]
