# Generated by Django 2.1 on 2018-11-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_auto_20181121_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorAlumnoRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_respuesta', to='aplicacion.Alumno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_respuesta', to='aplicacion.Alumno')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Respuesta')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumnorespuesta',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='alumnorespuesta',
            name='respuesta',
        ),
        migrations.DeleteModel(
            name='AlumnoRespuesta',
        ),
    ]
